name: Default branch

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/tests.yml
  release:
    name: Publish release
    needs: [tests]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Create release
        run: npx -p @release-it/bumper -p @release-it/conventional-changelog release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts for publication
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
  test-pypi:
    name: Publish to Test PyPI
    needs: [release]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/pydantic-gitlab-webhooks
    steps:
      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  pypi:
    name: Publish to PyPI
    needs: [test-pypi]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/pydantic-gitlab-webhooks
    steps:
      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
