name: Default branch

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      id-token: write
