name: Main

on:
  push:

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write
