on:
  workflow_call:
    environment-name:
      required: true
      type: string
    environment-url:
      required: true
      type: string
    repository-url:
      required: true
      type: string

jobs:
  publish:
    name: Publish PyPI package
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}
    steps:
      - name: Download assets
        uses: robinraju/release-downloader@v1
        with:
          tag: "${{ github.tag }}"
          out-file-path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.repository-url }}
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-24.04
    needs: [test-pypi-publish]
    environment:
      name: pypi
      url: https://pypi.org/p/pydantic-gitlab-webhooks
    permissions:
      id-token: write
    steps:
      - name: Download assets
        uses: robinraju/release-downloader@v1
        with:
          tag: "${{ github.tag }}"
          out-file-path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
