name: Release

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # Required to allow release-it to create releases
      contents: write
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Create release
        run: npx -p @release-it/bumper -p @release-it/conventional-changelog release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts for publication
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
  test-pypi-publish:
    name: Upload to Test PyPI
    runs-on: ubuntu-latest
    needs: [release]
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/pydantic-gitlab-webhooks
    permissions:
      id-token: write
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs: [test-pypi-publish]
    environment:
      name: pypi
      url: https://pypi.org/p/pydantic-gitlab-webhooks
    permissions:
      id-token: write
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
