name: Tests

on:
  workflow_call:
  push:
    branches-ignore: [main]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit
  commitlint:
    name: commitlint
    runs-on: ubuntu-24.04
    steps:
      - uses: wagoid/commitlint-github-action@v6
  pytest:
    name: pytest
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: poetry run pytest -v
  mkdocs:
    name: build documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build the documentation
        run: |
          poetry run mkdocs build
          touch site/.nojekyll
      - name: Upload GitHub pages artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
